### ISSUE TITLE
Feature Request - Use --purge option on azd down

### ISSUE THREAD

**Issue by MarcoABCardoso** [microsoft/template-validation-action#60]
Currently, running the validator creates and deletes resources, but some Azure resources are soft-deleted, causing a re-run to fail.

My suggestion would be to run `azd down` with the `--purge` option to prevent this issue.

**Comment by LianwMS** [comment]
Added:  https://github.com/microsoft/template-validation-action/blob/e1206403a3695eb48b4426e3ec8b1919101ac770/src/validator/azd_validator.py#L90
